extends CanvasLayer

# AUTO-GENERATED by sdk/game_engine/provisioning/loading_screen.py.
# Do NOT edit by hand -- regenerated on every build from the canonical
# template. Per-game theming flows through res://assets/ui/theme.tres
# (ProgressBar/fill stylebox color), so Claude's creative control over
# the bar accent works without touching this file.
#
# Layout rules baked in (see .claude/skills/godot-loading-screen):
#   R1: wordmark uses explicit anchors symmetric around 0.5
#   R2: bottom band anchored to viewport bottom with NEGATIVE offset_top
#   R3: autoload owns PRELOAD_PATHS + _cache + _busy + calls
#       change_scene_to_packed (not _to_file)

# Filled in at engine provisioning time by walking the game's assets/ and
# scenes/. Ordered small/fast -> big/slow so the bar fills smoothly as
# the slower assets land at the end.
const PRELOAD_PATHS: PackedStringArray = [
	# -- Scenes --
	"res://scenes/world/activity_beacon.tscn",
	"res://scenes/combat/player/basic_shockwave.tscn",
	"res://scenes/combat/player/basic_thunder_sphere.tscn",
	"res://scenes/entities/boss.tscn",
	"res://scenes/combat/enemy/boss_projectile.tscn",
	"res://scenes/combat/enemy/boss_telegraph.tscn",
	"res://scenes/entities/enemy.tscn",
	"res://scenes/combat/enemy/enemy_projectile.tscn",
	"res://scenes/combat/player/fire_ring.tscn",
	"res://scenes/world/game_world.tscn",
	"res://scenes/pickups/gold_drop.tscn",
	"res://scenes/pickups/loot_chest.tscn",
	"res://scenes/combat/player/magic_bolt.tscn",
	"res://scenes/main.tscn",
	"res://scenes/combat/player/melee_swing.tscn",
	"res://scenes/pickups/merchant.tscn",
	"res://scenes/entities/necro_minion.tscn",
	"res://scenes/entities/player.tscn",
	"res://scenes/entities/remote_player.tscn",
	"res://scenes/skills/skill_battle_cry.tscn",
	"res://scenes/skills/skill_caltrops.tscn",
	"res://scenes/skills/skill_chain_lightning.tscn",
	"res://scenes/skills/skill_composed.tscn",
	"res://scenes/skills/skill_druid_bite.tscn",
	"res://scenes/skills/skill_druid_charge.tscn",
	"res://scenes/skills/skill_druid_dire_wolf_form.tscn",
	"res://scenes/skills/skill_druid_eagle_form.tscn",
	"res://scenes/skills/skill_druid_hurricane.tscn",
	"res://scenes/skills/skill_druid_leap.tscn",
	"res://scenes/skills/skill_druid_stone_armor.tscn",
	"res://scenes/skills/skill_druid_summon_spirit.tscn",
	"res://scenes/skills/skill_druid_sweep.tscn",
	"res://scenes/skills/skill_druid_talon_swoop.tscn",
	"res://scenes/skills/skill_druid_wind_gust.tscn",
	"res://scenes/skills/skill_earthquake.tscn",
	"res://scenes/combat/player/skill_fire_wall.tscn",
	"res://scenes/skills/skill_hexen_blood_whip.tscn",
	"res://scenes/skills/skill_hexen_crimson_ritual.tscn",
	"res://scenes/skills/skill_hexen_hex_mark.tscn",
	"res://scenes/skills/skill_hexen_soul_tether.tscn",
	"res://scenes/combat/player/skill_ice_bolt.tscn",
	"res://scenes/skills/skill_leap_slam.tscn",
	"res://scenes/skills/skill_meteor.tscn",
	"res://scenes/skills/skill_necro_blood_pact.tscn",
	"res://scenes/skills/skill_necro_bone_spear.tscn",
	"res://scenes/skills/skill_necro_curse_field.tscn",
	"res://scenes/skills/skill_necro_death_pulse.tscn",
	"res://scenes/skills/skill_necro_raise_knight.tscn",
	"res://scenes/skills/skill_necro_raise_skeleton.tscn",
	"res://scenes/combat/player/skill_poison_vial.tscn",
	"res://scenes/skills/skill_smoke_bomb.tscn",
	"res://scenes/skills/skill_storm_chain_bolt.tscn",
	"res://scenes/skills/skill_storm_sky_strike.tscn",
	"res://scenes/skills/skill_storm_static_discharge.tscn",
	"res://scenes/skills/skill_storm_step.tscn",
	"res://scenes/combat/player/skill_whirlwind.tscn",
	"res://scenes/entities/spirit_pet.tscn",
	"res://scenes/combat/player/thrown_dagger.tscn",
	"res://scenes/ui/character_sheet.tscn",
	"res://scenes/ui/class_selector.tscn",
	"res://scenes/ui/game_over.tscn",
	"res://scenes/ui/hud.tscn",
	"res://scenes/ui/level_up_choice.tscn",
	"res://scenes/ui/loot_roulette.tscn",
	"res://scenes/ui/merchant_panel.tscn",
	"res://scenes/ui/multiplayer_lobby.tscn",
	"res://scenes/ui/pause_menu.tscn",
	"res://scenes/ui/trade_panel.tscn",
	"res://scenes/pickups/wave_portal.tscn",
	"res://scenes/pickups/xp_drop.tscn",
	# -- UI / textures / themes / fonts --
	"res://assets/ui/app_icon.webp",
	"res://assets/ui/banner.webp",
	"res://assets/ui/btn_back.png",
	"res://assets/ui/btn_back.tres",
	"res://assets/ui/btn_blank.png",
	"res://assets/ui/btn_blank.tres",
	"res://assets/ui/btn_choose.png",
	"res://assets/ui/btn_choose.tres",
	"res://assets/ui/btn_play.png",
	"res://assets/ui/btn_play.tres",
	"res://assets/ui/btn_quit.png",
	"res://assets/ui/btn_quit.tres",
	"res://assets/ui/cover.webp",
	"res://assets/ui/cover_sm.webp",
	"res://assets/ui/icon_dexterity.png",
	"res://assets/ui/icon_gold.png",
	"res://assets/ui/icon_heart.png",
	"res://assets/ui/icon_intelligence.png",
	"res://assets/ui/icon_mana.png",
	"res://assets/ui/icon_strength.png",
	"res://assets/ui/loading_bar_accent.tres",
	"res://assets/ui/loading_screen.webp",
	"res://assets/ui/panel_card.png",
	"res://assets/ui/panel_card.tres",
	"res://assets/ui/panel_dialog.webp",
	"res://assets/ui/panel_dialog.tres",
	"res://assets/ui/panel_hud.png",
	"res://assets/ui/panel_hud.tres",
	"res://assets/ui/panel_main.png",
	"res://assets/ui/panel_main.tres",
	"res://assets/ui/theme.tres",
	"res://assets/ui/title_poster.webp",
	"res://assets/ui/title_poster_sm.webp",
	"res://assets/ui/wordmark_title.webp",
	# -- World textures --
	"res://assets/sprites/characters/archmage/archmage_attack.png",
	"res://assets/sprites/characters/archmage/archmage_idle.png",
	"res://assets/sprites/characters/archmage/archmage_walk.png",
	"res://assets/sprites/characters/barbarian/barbarian_attack.png",
	"res://assets/sprites/characters/barbarian/barbarian_idle.png",
	"res://assets/sprites/characters/barbarian/barbarian_walk.png",
	"res://assets/sprites/characters/boss_crimson_matron_idle.png",
	"res://assets/sprites/characters/boss_hellgate_sovereign_idle.png",
	"res://assets/sprites/characters/boss_lich_empress_idle.png",
	"res://assets/sprites/characters/boss_shadewitch_idle.png",
	"res://assets/sprites/characters/crimson_hexen_attack.png",
	"res://assets/sprites/characters/crimson_hexen_idle.png",
	"res://assets/sprites/characters/crimson_hexen_walk.png",
	"res://assets/sprites/characters/dark_cultist/dark_cultist_attack.png",
	"res://assets/sprites/characters/dark_cultist/dark_cultist_idle.png",
	"res://assets/sprites/characters/dark_cultist/dark_cultist_walk.png",
	"res://assets/sprites/characters/druid_bear_attack.png",
	"res://assets/sprites/characters/druid_bear_idle.png",
	"res://assets/sprites/characters/druid_bear_walk.png",
	"res://assets/sprites/characters/druid_eagle_attack.png",
	"res://assets/sprites/characters/druid_eagle_idle.png",
	"res://assets/sprites/characters/druid_eagle_walk.png",
	"res://assets/sprites/characters/druid_human_attack.png",
	"res://assets/sprites/characters/druid_human_idle.png",
	"res://assets/sprites/characters/druid_human_walk.png",
	"res://assets/sprites/characters/druid_wolf_attack.png",
	"res://assets/sprites/characters/druid_wolf_idle.png",
	"res://assets/sprites/characters/druid_wolf_walk.png",
	"res://assets/sprites/characters/merchant_idle.png",
	"res://assets/sprites/characters/necro_skeleton_attack.png",
	"res://assets/sprites/characters/necro_skeleton_idle.png",
	"res://assets/sprites/characters/necro_skeleton_knight_attack.png",
	"res://assets/sprites/characters/necro_skeleton_knight_idle.png",
	"res://assets/sprites/characters/necro_skeleton_knight_walk.png",
	"res://assets/sprites/characters/necro_skeleton_walk.png",
	"res://assets/sprites/characters/necromancer_attack.png",
	"res://assets/sprites/characters/necromancer_idle.png",
	"res://assets/sprites/characters/necromancer_walk.png",
	"res://assets/sprites/characters/rogue/rogue_attack.png",
	"res://assets/sprites/characters/rogue/rogue_idle.png",
	"res://assets/sprites/characters/rogue/rogue_walk.png",
	"res://assets/sprites/characters/ruin_wraith/ruin_wraith_attack.png",
	"res://assets/sprites/characters/ruin_wraith/ruin_wraith_idle.png",
	"res://assets/sprites/characters/ruin_wraith/ruin_wraith_walk.png",
	"res://assets/sprites/characters/skeleton_warrior/skeleton_warrior_attack.png",
	"res://assets/sprites/characters/skeleton_warrior/skeleton_warrior_idle.png",
	"res://assets/sprites/characters/skeleton_warrior/skeleton_warrior_walk.png",
	"res://assets/sprites/characters/spider_brood_attack.png",
	"res://assets/sprites/characters/spider_brood_idle.png",
	"res://assets/sprites/characters/spider_brood_walk.png",
	"res://assets/sprites/characters/spider_hatchling_attack.png",
	"res://assets/sprites/characters/spider_hatchling_idle.png",
	"res://assets/sprites/characters/spider_hatchling_walk.png",
	"res://assets/sprites/characters/spirit_bear_attack.png",
	"res://assets/sprites/characters/spirit_bear_idle.png",
	"res://assets/sprites/characters/spirit_bear_walk.png",
	"res://assets/sprites/characters/spirit_wolf_attack.png",
	"res://assets/sprites/characters/spirit_wolf_idle.png",
	"res://assets/sprites/characters/spirit_wolf_walk.png",
	"res://assets/sprites/characters/stormcaller_attack.png",
	"res://assets/sprites/characters/stormcaller_idle.png",
	"res://assets/sprites/characters/stormcaller_walk.png",
	"res://assets/sprites/characters/succubus_attack.png",
	"res://assets/sprites/characters/succubus_idle.png",
	"res://assets/sprites/characters/succubus_walk.png",
	"res://assets/sprites/effects/bone_lance_thrust.png",
	"res://assets/sprites/effects/bone_shard.png",
	"res://assets/sprites/effects/bone_spear_projectile.png",
	"res://assets/sprites/effects/bone_spire.png",
	"res://assets/sprites/effects/boss_telegraph_circle.png",
	"res://assets/sprites/effects/boss_telegraph_cone.png",
	"res://assets/sprites/effects/boss_telegraph_line.png",
	"res://assets/sprites/effects/caltrop_spike.png",
	"res://assets/sprites/effects/cast_flash.png",
	"res://assets/sprites/effects/crimson_ritual_zone.png",
	"res://assets/sprites/effects/curse_field_zone.png",
	"res://assets/sprites/effects/dagger_impact.png",
	"res://assets/sprites/effects/dark_beam.png",
	"res://assets/sprites/effects/dark_bolt.png",
	"res://assets/sprites/effects/death_pulse_ring.png",
	"res://assets/sprites/effects/explosion_orange.png",
	"res://assets/sprites/effects/fire_flame.png",
	"res://assets/sprites/effects/hellbolt_projectile.png",
	"res://assets/sprites/effects/hex_mark_aura.png",
	"res://assets/sprites/effects/hurricane_vfx.png",
	"res://assets/sprites/effects/ice_bolt.png",
	"res://assets/sprites/effects/ice_shard.png",
	"res://assets/sprites/effects/lightning_bolt_segment.png",
	"res://assets/sprites/effects/lightning_zap.png",
	"res://assets/sprites/effects/mage_phantom_sword.png",
	"res://assets/sprites/effects/magic_bolt.png",
	"res://assets/sprites/effects/melee_swing_arc.png",
	"res://assets/sprites/effects/meteor_rock.png",
	"res://assets/sprites/effects/meteor_telegraph.png",
	"res://assets/sprites/effects/poison_cloud.png",
	"res://assets/sprites/effects/portal_continue.png",
	"res://assets/sprites/effects/rage_aura.png",
	"res://assets/sprites/effects/shockwave_basic.png",
	"res://assets/sprites/effects/sky_strike_bolt.png",
	"res://assets/sprites/effects/sky_strike_telegraph.png",
	"res://assets/sprites/effects/smoke_puff_purple.png",
	"res://assets/sprites/effects/soul_tether_chain.png",
	"res://assets/sprites/effects/soul_wisp.png",
	"res://assets/sprites/effects/static_discharge_nova.png",
	"res://assets/sprites/effects/stone_armor_chunk.png",
	"res://assets/sprites/effects/succubus_aoe_telegraph.png",
	"res://assets/sprites/effects/succubus_kiss_blast.png",
	"res://assets/sprites/effects/thrown_dagger.png",
	"res://assets/sprites/effects/thunder_sphere.png",
	"res://assets/sprites/items/column_broken.png",
	"res://assets/sprites/items/column_standing.png",
	"res://assets/sprites/items/crystal_blue.png",
	"res://assets/sprites/items/crystal_purple.png",
	"res://assets/sprites/items/gear_amulet_pendant.png",
	"res://assets/sprites/items/gear_boots_greaves.png",
	"res://assets/sprites/items/gear_chest_plate.png",
	"res://assets/sprites/items/gear_gloves_gauntlets.png",
	"res://assets/sprites/items/gear_helmet_iron.png",
	"res://assets/sprites/items/gear_ring_signet.png",
	"res://assets/sprites/items/icon_barb_cry.png",
	"res://assets/sprites/items/icon_barb_leap.png",
	"res://assets/sprites/items/icon_barb_quake.png",
	"res://assets/sprites/items/icon_barb_whirlwind.png",
	"res://assets/sprites/items/icon_dash.png",
	"res://assets/sprites/items/icon_druid_bear_form.png",
	"res://assets/sprites/items/icon_druid_bite.png",
	"res://assets/sprites/items/icon_druid_charge.png",
	"res://assets/sprites/items/icon_druid_dire_wolf.png",
	"res://assets/sprites/items/icon_druid_eagle_form.png",
	"res://assets/sprites/items/icon_druid_hurricane.png",
	"res://assets/sprites/items/icon_druid_leap.png",
	"res://assets/sprites/items/icon_druid_stone_armor.png",
	"res://assets/sprites/items/icon_druid_summon_spirit.png",
	"res://assets/sprites/items/icon_druid_sweep.png",
	"res://assets/sprites/items/icon_druid_talon_swoop.png",
	"res://assets/sprites/items/icon_druid_wind_gust.png",
	"res://assets/sprites/items/icon_druid_wolf_form.png",
	"res://assets/sprites/items/icon_hexen_blood_whip.png",
	"res://assets/sprites/items/icon_hexen_bloodmoon.png",
	"res://assets/sprites/items/icon_hexen_crimson_ritual.png",
	"res://assets/sprites/items/icon_hexen_eternal_mark.png",
	"res://assets/sprites/items/icon_hexen_hex_mark.png",
	"res://assets/sprites/items/icon_hexen_soul_tether.png",
	"res://assets/sprites/items/icon_hexen_tether_shock.png",
	"res://assets/sprites/items/icon_necro_blood_pact.png",
	"res://assets/sprites/items/icon_necro_bone_spear.png",
	"res://assets/sprites/items/icon_necro_curse_field.png",
	"res://assets/sprites/items/icon_necro_death_pulse.png",
	"res://assets/sprites/items/icon_necro_raise_knight.png",
	"res://assets/sprites/items/icon_necro_raise_skeleton.png",
	"res://assets/sprites/items/icon_rogue_caltrops.png",
	"res://assets/sprites/items/icon_rogue_knives.png",
	"res://assets/sprites/items/icon_rogue_poison.png",
	"res://assets/sprites/items/icon_rogue_smoke.png",
	"res://assets/sprites/items/icon_skill_basic.png",
	"res://assets/sprites/items/icon_skill_chain_lightning.png",
	"res://assets/sprites/items/icon_skill_fire_wall.png",
	"res://assets/sprites/items/icon_skill_ice_bolt.png",
	"res://assets/sprites/items/icon_skill_meteor.png",
	"res://assets/sprites/items/icon_skill_ult.png",
	"res://assets/sprites/items/icon_storm_capacitor_core.png",
	"res://assets/sprites/items/icon_storm_chain_bolt.png",
	"res://assets/sprites/items/icon_storm_heavens_spear.png",
	"res://assets/sprites/items/icon_storm_sky_strike.png",
	"res://assets/sprites/items/icon_storm_static_discharge.png",
	"res://assets/sprites/items/icon_storm_step.png",
	"res://assets/sprites/items/icon_storm_stormveil.png",
	"res://assets/sprites/items/icon_unique_basic_bone_lance.png",
	"res://assets/sprites/items/icon_unique_basic_phantom_edge.png",
	"res://assets/sprites/items/icon_unique_basic_shockwave.png",
	"res://assets/sprites/items/icon_unique_basic_thunder_sphere.png",
	"res://assets/sprites/items/icon_unique_basic_triple_throw.png",
	"res://assets/sprites/items/icon_unique_basic_voltaic_tonfa.png",
	"res://assets/sprites/items/icon_unique_basic_whipcrack.png",
	"res://assets/sprites/items/loot_chest_closed.png",
	"res://assets/sprites/items/portrait_barbarian.png",
	"res://assets/sprites/items/portrait_crimson_hexen.webp",
	"res://assets/sprites/items/portrait_druid.webp",
	"res://assets/sprites/items/portrait_mage.png",
	"res://assets/sprites/items/portrait_necromancer.webp",
	"res://assets/sprites/items/portrait_rogue.png",
	"res://assets/sprites/items/portrait_stormcaller.webp",
	"res://assets/sprites/items/rune_circle.png",
	"res://assets/sprites/items/statue_guardian.png",
	"res://assets/sprites/items/torch.png",
	"res://assets/sprites/items/unique_berserker_halo.png",
	"res://assets/sprites/items/unique_crimson_aegis.png",
	"res://assets/sprites/items/unique_frostwalker.png",
	"res://assets/sprites/items/unique_mark_of_coil.png",
	"res://assets/sprites/items/unique_phantom_soles.png",
	"res://assets/sprites/items/unique_pyrocrown.png",
	"res://assets/sprites/items/unique_quakegrasp_gauntlets.png",
	"res://assets/sprites/items/unique_storm_sigil.png",
	"res://assets/sprites/items/unique_venomweave.png",
	"res://assets/sprites/items/unique_voidstaff.png",
	"res://assets/sprites/items/unique_whisper_edge.png",
	"res://assets/sprites/items/unique_worldcleaver.png",
	"res://assets/sprites/items/weapon_barb_1h_axe.png",
	"res://assets/sprites/items/weapon_barb_2h_axe.png",
	"res://assets/sprites/items/weapon_mage_staff.png",
	"res://assets/sprites/items/weapon_mage_wand.png",
	"res://assets/sprites/items/weapon_rogue_bow.png",
	"res://assets/sprites/items/weapon_rogue_dagger.png",
	"res://assets/sprites/pickups/gold_coin.png",
	"res://assets/sprites/pickups/xp_orb.png",
	"res://assets/textures/backgrounds/inventory_bg_dark.webp",
	"res://assets/textures/backgrounds/menu_background.webp",
	"res://assets/textures/floors/ruins_floor.webp",
	"res://assets/textures/walls/ruins_wall.webp",
	# -- Audio (music, SFX, ambient) --
	"res://assets/audio/ambient/ambient_dungeon_dungeon_ambient.mp3",
	"res://assets/audio/music/music_boss_music_boss.mp3",
	"res://assets/audio/music/music_combat_dungeon_combat.mp3",
	"res://assets/audio/music/music_exploration_dungeon_explore.mp3",
	"res://assets/audio/sfx/enemy/enemy_boss_appear.mp3",
	"res://assets/audio/sfx/enemy/enemy_boss_death.mp3",
	"res://assets/audio/sfx/enemy/enemy_boss_phase_transition.mp3",
	"res://assets/audio/sfx/enemy/enemy_boss_telegraph_warn.mp3",
	"res://assets/audio/sfx/enemy/enemy_enemy_death_cultist.mp3",
	"res://assets/audio/sfx/enemy/enemy_enemy_death_skeleton.mp3",
	"res://assets/audio/sfx/enemy/enemy_enemy_death_skeleton_knight.mp3",
	"res://assets/audio/sfx/enemy/enemy_enemy_death_spider_brood.mp3",
	"res://assets/audio/sfx/enemy/enemy_enemy_death_spider_hatchling.mp3",
	"res://assets/audio/sfx/enemy/enemy_enemy_death_succubus.mp3",
	"res://assets/audio/sfx/enemy/enemy_enemy_death_wraith.mp3",
	"res://assets/audio/sfx/enemy/enemy_enemy_hurt.mp3",
	"res://assets/audio/sfx/enemy/enemy_spider_hatchling_spawn.mp3",
	"res://assets/audio/sfx/enemy/enemy_succubus_aoe_blast.mp3",
	"res://assets/audio/sfx/enemy/enemy_succubus_attack_charge.mp3",
	"res://assets/audio/sfx/pickup/pickup_gold_pickup.mp3",
	"res://assets/audio/sfx/pickup/pickup_xp_pickup.mp3",
	"res://assets/audio/sfx/player/player_basic_bone_lance.mp3",
	"res://assets/audio/sfx/player/player_basic_phantom_swing.mp3",
	"res://assets/audio/sfx/player/player_basic_shockwave.mp3",
	"res://assets/audio/sfx/player/player_basic_thunder_sphere.mp3",
	"res://assets/audio/sfx/player/player_dagger_hit.mp3",
	"res://assets/audio/sfx/player/player_dagger_throw.mp3",
	"res://assets/audio/sfx/player/player_druid_bear_charge.mp3",
	"res://assets/audio/sfx/player/player_druid_bear_sweep.mp3",
	"res://assets/audio/sfx/player/player_druid_bite_hit.mp3",
	"res://assets/audio/sfx/player/player_druid_hurricane.mp3",
	"res://assets/audio/sfx/player/player_druid_stone_armor_break.mp3",
	"res://assets/audio/sfx/player/player_druid_stone_armor_form.mp3",
	"res://assets/audio/sfx/player/player_druid_summon_spirit.mp3",
	"res://assets/audio/sfx/player/player_druid_talon_swoop.mp3",
	"res://assets/audio/sfx/player/player_druid_transform_bear.mp3",
	"res://assets/audio/sfx/player/player_druid_transform_eagle.mp3",
	"res://assets/audio/sfx/player/player_druid_transform_revert.mp3",
	"res://assets/audio/sfx/player/player_druid_transform_wolf.mp3",
	"res://assets/audio/sfx/player/player_druid_wind_gust.mp3",
	"res://assets/audio/sfx/player/player_druid_wolf_leap.mp3",
	"res://assets/audio/sfx/player/player_footstep_stone.mp3",
	"res://assets/audio/sfx/player/player_hexen_blood_whip.mp3",
	"res://assets/audio/sfx/player/player_hexen_crimson_ritual.mp3",
	"res://assets/audio/sfx/player/player_hexen_hex_mark_apply.mp3",
	"res://assets/audio/sfx/player/player_hexen_hex_mark_detonate.mp3",
	"res://assets/audio/sfx/player/player_hexen_soul_tether.mp3",
	"res://assets/audio/sfx/player/player_level_up.mp3",
	"res://assets/audio/sfx/player/player_magic_cast.mp3",
	"res://assets/audio/sfx/player/player_magic_hit.mp3",
	"res://assets/audio/sfx/player/player_melee_hit.mp3",
	"res://assets/audio/sfx/player/player_melee_swing.mp3",
	"res://assets/audio/sfx/player/player_necro_blood_pact.mp3",
	"res://assets/audio/sfx/player/player_necro_bone_spear.mp3",
	"res://assets/audio/sfx/player/player_necro_curse_field.mp3",
	"res://assets/audio/sfx/player/player_necro_death_pulse.mp3",
	"res://assets/audio/sfx/player/player_necro_raise_knight.mp3",
	"res://assets/audio/sfx/player/player_necro_raise_skeleton.mp3",
	"res://assets/audio/sfx/player/player_spell_battlecry.mp3",
	"res://assets/audio/sfx/player/player_spell_caltrops.mp3",
	"res://assets/audio/sfx/player/player_spell_chain_lightning.mp3",
	"res://assets/audio/sfx/player/player_spell_dash_short.mp3",
	"res://assets/audio/sfx/player/player_spell_dash_teleport.mp3",
	"res://assets/audio/sfx/player/player_spell_earthquake.mp3",
	"res://assets/audio/sfx/player/player_spell_fan_knives.mp3",
	"res://assets/audio/sfx/player/player_spell_fire_wall.mp3",
	"res://assets/audio/sfx/player/player_spell_ice_bolt.mp3",
	"res://assets/audio/sfx/player/player_spell_leap.mp3",
	"res://assets/audio/sfx/player/player_spell_meteor.mp3",
	"res://assets/audio/sfx/player/player_spell_poison.mp3",
	"res://assets/audio/sfx/player/player_spell_smoke_bomb.mp3",
	"res://assets/audio/sfx/player/player_spell_whirlwind.mp3",
	"res://assets/audio/sfx/player/player_storm_chain_bolt.mp3",
	"res://assets/audio/sfx/player/player_storm_sky_strike_hit.mp3",
	"res://assets/audio/sfx/player/player_storm_sky_strike_warn.mp3",
	"res://assets/audio/sfx/player/player_storm_static_discharge.mp3",
	"res://assets/audio/sfx/player/player_storm_step_dash.mp3",
	"res://assets/audio/sfx/ui/ui_equip_armor.mp3",
	"res://assets/audio/sfx/ui/ui_loot_reveal_common.mp3",
	"res://assets/audio/sfx/ui/ui_loot_reveal_legendary.mp3",
	"res://assets/audio/sfx/ui/ui_loot_reveal_rare.mp3",
	"res://assets/audio/sfx/ui/ui_loot_reveal_unique.mp3",
	"res://assets/audio/sfx/ui/ui_loot_roulette_tick.mp3",
	"res://assets/audio/sfx/ui/ui_merchant_fail.mp3",
	"res://assets/audio/sfx/ui/ui_merchant_greeting.mp3",
	"res://assets/audio/sfx/ui/ui_merchant_purchase.mp3",
	"res://assets/audio/sfx/ui/ui_merchant_upgrade.mp3",
	"res://assets/audio/sfx/ui/ui_salvage_dust.mp3",
	"res://assets/audio/sfx/ui/ui_ui_menu_click.mp3",
]

# DEFAULT_ACCENT is the fallback bar-fill color when assets/ui/theme.tres
# doesn't ship a ProgressBar/fill stylebox. Picked to look reasonable on
# a black background.
const DEFAULT_ACCENT := Color(0.96, 0.70, 0.45, 1.0)
const DEFAULT_BG := Color(0.08, 0.08, 0.10, 0.85)

var _cache: Dictionary = {}
var _preloaded: bool = false
var _busy: bool = false

var _root: Control
var _progress: ProgressBar
var _status: Label


func _ready() -> void:
	layer = 100
	process_mode = Node.PROCESS_MODE_ALWAYS
	visible = false
	_build_ui()


# Per-game accent resolution. Three lookups in priority order:
#
#  1. assets/ui/loading_bar_accent.tres  -- a StyleBoxFlat written by
#     Claude after generate_ui_kit, with bg_color matching the kit's
#     accent. This is the primary mechanism (see godot-loading-screen
#     skill).
#
#  2. assets/ui/theme.tres "ProgressBar/styles/fill" stylebox --
#     forward-compat for when/if generate_ui_kit ever synthesizes a
#     ProgressBar slot directly. Currently it doesn't, so this branch
#     is dormant but kept so a future upstream change Just Works.
#
#  3. DEFAULT_ACCENT -- neutral fallback when neither file is present
#     (e.g. a game that skipped the UI kit step).
func _resolve_accent() -> Color:
	if ResourceLoader.exists("res://assets/ui/loading_bar_accent.tres"):
		var sb := load("res://assets/ui/loading_bar_accent.tres") as StyleBoxFlat
		if sb:
			return sb.bg_color
	if ResourceLoader.exists("res://assets/ui/theme.tres"):
		var t := load("res://assets/ui/theme.tres") as Theme
		if t:
			var fill := t.get_stylebox("fill", "ProgressBar") as StyleBoxFlat
			if fill:
				return fill.bg_color
	return DEFAULT_ACCENT


func _build_ui() -> void:
	_root = Control.new()
	add_child(_root)
	_root.set_anchors_and_offsets_preset(Control.PRESET_FULL_RECT)
	_root.mouse_filter = Control.MOUSE_FILTER_IGNORE

	# Solid black backdrop -- no grey flash even if the scenery image is
	# missing or still importing.
	var bg := ColorRect.new()
	bg.color = Color.BLACK
	_root.add_child(bg)
	bg.set_anchors_and_offsets_preset(Control.PRESET_FULL_RECT)

	# Scenery image (loaded at runtime so we don't crash if missing).
	if ResourceLoader.exists("res://assets/ui/loading_screen.webp"):
		var img := TextureRect.new()
		img.texture = load("res://assets/ui/loading_screen.webp")
		img.stretch_mode = TextureRect.STRETCH_KEEP_ASPECT_COVERED
		img.expand_mode = TextureRect.EXPAND_IGNORE_SIZE
		_root.add_child(img)
		img.set_anchors_and_offsets_preset(Control.PRESET_FULL_RECT)

	# Subtle vignette so the wordmark and bar read against busy scenery.
	var vignette := ColorRect.new()
	vignette.color = Color(0, 0, 0, 0.30)
	_root.add_child(vignette)
	vignette.set_anchors_and_offsets_preset(Control.PRESET_FULL_RECT)

	# Wordmark -- R1: explicit anchors, symmetric around 0.5. No
	# CenterContainer wrapper (would collapse on a CanvasLayer).
	if ResourceLoader.exists("res://assets/ui/wordmark_title.webp"):
		var wm := TextureRect.new()
		wm.texture = load("res://assets/ui/wordmark_title.webp")
		wm.stretch_mode = TextureRect.STRETCH_KEEP_ASPECT_CENTERED
		wm.expand_mode = TextureRect.EXPAND_FIT_WIDTH_PROPORTIONAL
		_root.add_child(wm)
		wm.anchor_left = 0.5
		wm.anchor_right = 0.5
		wm.anchor_top = 0.0
		wm.anchor_bottom = 0.0
		wm.offset_left = -450
		wm.offset_right = 450
		wm.offset_top = 80
		wm.offset_bottom = 380

	# Bottom band -- R2: anchor_top = anchor_bottom = 1.0, NEGATIVE
	# offset_top so the band sits INSIDE the viewport (not below).
	var band := Control.new()
	_root.add_child(band)
	band.anchor_left = 0.5
	band.anchor_right = 0.5
	band.anchor_top = 1.0
	band.anchor_bottom = 1.0
	band.offset_left = -360
	band.offset_right = 360
	band.offset_top = -160
	band.offset_bottom = -40

	var vbox := VBoxContainer.new()
	band.add_child(vbox)
	vbox.set_anchors_and_offsets_preset(Control.PRESET_FULL_RECT)
	vbox.add_theme_constant_override("separation", 12)

	_status = Label.new()
	_status.text = "Загрузка..."
	_status.horizontal_alignment = HORIZONTAL_ALIGNMENT_CENTER
	vbox.add_child(_status)

	# ProgressBar with explicit StyleBoxFlat overrides. The kit theme.tres
	# may not ship a ProgressBar style, in which case the default Godot
	# fill renders grey-on-grey and the bar looks stuck at 0%. Accent
	# comes from theme.tres "ProgressBar/fill" if available; else default.
	var accent := _resolve_accent()
	_progress = ProgressBar.new()
	_progress.min_value = 0.0
	_progress.max_value = 1.0
	_progress.show_percentage = false
	_progress.custom_minimum_size = Vector2(0, 22)
	var pb_bg := StyleBoxFlat.new()
	pb_bg.bg_color = DEFAULT_BG
	pb_bg.set_corner_radius_all(6)
	var pb_fill := StyleBoxFlat.new()
	pb_fill.bg_color = accent
	pb_fill.set_corner_radius_all(6)
	_progress.add_theme_stylebox_override("background", pb_bg)
	_progress.add_theme_stylebox_override("fill", pb_fill)
	vbox.add_child(_progress)


func _show() -> void:
	visible = true
	set_progress(0.0)


func _hide() -> void:
	visible = false


func set_progress(p: float) -> void:
	if _progress:
		_progress.value = clamp(p, 0.0, 1.0)
	if _status:
		_status.text = "Загрузка... %d%%" % int(p * 100.0)


# Heavy first-time warm-up. Honors a min_display floor so quick loads
# still show the screen long enough for the player to read.
func preload_and_change_scene(scene_path: String, min_display: float = 1.5) -> void:
	if _busy:
		return
	_busy = true
	_show()
	var t0 := Time.get_ticks_msec()
	await get_tree().process_frame
	await get_tree().process_frame  # double-frame render guarantee
	if not _preloaded:
		await _run_preload_sequence()  # fills 0% -> 92%
		_preloaded = true
	await _change_scene_to(scene_path)  # fills 92% -> 100%
	var elapsed := float(Time.get_ticks_msec() - t0) / 1000.0
	if elapsed < min_display:
		await get_tree().create_timer(min_display - elapsed).timeout
	_hide()
	_busy = false


# Fast subsequent transition. Uses the cached PackedScene if it was
# warmed in the first preload pass; otherwise falls back to a fresh load.
func change_scene(scene_path: String, min_display: float = 0.6) -> void:
	if _busy:
		return
	_busy = true
	_show()
	var t0 := Time.get_ticks_msec()
	await get_tree().process_frame
	await get_tree().process_frame
	await _change_scene_to(scene_path)
	var elapsed := float(Time.get_ticks_msec() - t0) / 1000.0
	if elapsed < min_display:
		await get_tree().create_timer(min_display - elapsed).timeout
	_hide()
	_busy = false


# Synchronous load() per asset with a process_frame yield between each
# iteration. We deliberately do NOT use ResourceLoader.load_threaded_*
# here -- on single-threaded web (Godot 4's default web export, which
# is what most games target), there is no background thread, so
# load_threaded_get_status returns THREAD_LOAD_LOADED immediately on
# the first poll. The inner `while` loop then breaks BEFORE any
# `await get_tree().process_frame`, the whole 50+ iteration sequence
# runs in a single frame, and the bar appears to jump from 0% to 92%
# in one paint -- exactly the symptom that motivated threading in the
# first place.
#
# The simpler synchronous pattern below yields one frame per asset
# (independent of cache hits / missing files / load() runtime), so the
# bar repaints smoothly on EVERY web export configuration. For
# multi-threaded web with SharedArrayBuffer the per-asset frame yield
# is the only thing the bar cares about anyway -- you don't gain
# meaningful parallelism on the main thread that owns the renderer.
func _run_preload_sequence() -> void:
	var total := PRELOAD_PATHS.size()
	if total == 0:
		set_progress(0.92)
		return
	for i in total:
		var path := PRELOAD_PATHS[i]
		if _cache.has(path) or not ResourceLoader.exists(path):
			set_progress(float(i + 1) / float(total) * 0.92)
			await get_tree().process_frame
			continue
		var res := load(path)
		if res:
			_cache[path] = res
		else:
			push_warning("LoadingScreen preload failed: " + path)
		# Reserve the last 8% for the actual scene swap.
		set_progress(float(i + 1) / float(total) * 0.92)
		await get_tree().process_frame


func _change_scene_to(scene_path: String) -> void:
	var packed := _cache.get(scene_path) as PackedScene
	if packed:
		get_tree().change_scene_to_packed(packed)
	else:
		get_tree().change_scene_to_file(scene_path)
	set_progress(1.0)
	await get_tree().process_frame
	await get_tree().process_frame
